package finalproject;

/**
 *
 * @author AFAQE
 */

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public static ArrayList<Hospital> hospitals;
    public static Map<String, ArrayList<Doctor>> doctors;
    public static ArrayList<Patient> patients;

    public MainGUI() {
        initComponents();
        hospitals = new ArrayList<Hospital>();
        doctors = new HashMap<String, ArrayList<Doctor>>();
        patients = new ArrayList<Patient>();
    }

    private static void addElement(Map<String, ArrayList<Doctor>> map, String key, Doctor value) {
        // Check if the key exists in the map
        if (map.containsKey(key)) {
            // Retrieve the ArrayList associated with the key
            ArrayList<Doctor> list = map.get(key);
            // Add the value to the ArrayList
            list.add(value);
        } else {
            // Create a new ArrayList and add the value to it
            ArrayList<Doctor> list = new ArrayList<>();
            list.add(value);
            // Put the ArrayList into the map, associating it with the key
            map.put(key, list);
        }
    }

    private static void Sort(Map<String, ArrayList<Doctor>> map, String key, Doctor value) {
        // Check if the key exists in the map
        if (map.containsKey(key)) {
            // Retrieve the ArrayList associated with the key
            ArrayList<Doctor> list = map.get(key);
            Collections.sort(list);
            map.put(key, list);
        } else {
            // Create a new ArrayList and add the value to it
            ArrayList<Doctor> list = new ArrayList<>();
            list.add(value);
            // Put the ArrayList into the map, associating it with the key
            map.put(key, list);
        }
    }

    public static void quickSort(ArrayList<Patient> arr, int low, int high) {
        if (low < high) {
            int pi = partition(arr, low, high);
            quickSort(arr, low, pi - 1);
            quickSort(arr, pi + 1, high);
        }
    }

    public static int partition(ArrayList<Patient> arr, int low, int high) {
        String pivot = arr.get(high).Id;
        int i = low - 1;
        for (int j = low; j < high; j++) {
            if (arr.get(j).Id.compareTo(pivot) < 0) {
                i++;
                Patient temp = arr.get(i);
                arr.set(i, arr.get(j));
                arr.set(j, temp);
            }
        }
        Patient temp = arr.get(i + 1);
        arr.set(i + 1, arr.get(high));
        arr.set(high, temp);

        return i + 1;
    }

    public static int binarySearchH(ArrayList<Hospital> arr, String target) {
        int left = 0, right = arr.size() - 1;
        while (left <= right) {
            int mid = left + (right - left) / 2;

            // Check if target is present at mid
            if (arr.get(mid).Name.compareTo(target) == 0) {
                return mid;
            }

            // If target greater, ignore left half
            if (arr.get(mid).Name.compareTo(target) < 0) {
                left = mid + 1;
            } else { // If target is smaller, ignore right half
                right = mid - 1;
            }
        }
        // If we reach here, then the element was not present
        return -1;
    }

    public static int binarySearchP(ArrayList<Patient> arr, String target) {
        int left = 0, right = arr.size() - 1;
        while (left <= right) {
            int mid = left + (right - left) / 2;

            // Check if target is present at mid
            if (arr.get(mid).Id.compareTo(target) == 0) {
                return mid;
            }

            // If target greater, ignore left half
            if (arr.get(mid).Id.compareTo(target) < 0) {
                left = mid + 1;
            } else { // If target is smaller, ignore right half
                right = mid - 1;
            }
        }
        // If we reach here, then the element was not present
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_Panal = new javax.swing.JPanel();
        Search = new javax.swing.JButton();
        Hospitale = new javax.swing.JButton();
        Doctor = new javax.swing.JButton();
        Patient = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Hospitale_Panel = new javax.swing.JPanel();
        Back_Hospitale = new javax.swing.JButton();
        Insert_Hospitale = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Hospital_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Hospital_Loc = new javax.swing.JTextField();
        View_Hospitales = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Doctor_Panel = new javax.swing.JPanel();
        Back_Doctor = new javax.swing.JButton();
        Doctor_Insert = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Doctor_ID = new javax.swing.JTextField();
        View_Doctors = new javax.swing.JButton();
        Doctor_Tele = new javax.swing.JTextField();
        Doctor_Name = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        DRSpecialization = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        Patient_Insert = new javax.swing.JButton();
        View_Patients = new javax.swing.JButton();
        Back_Patients = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Patient_ID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Patient_Age = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Patient_Name = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Patient_Tele = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Hosts_Table = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        Hospitale_Back_To_Search = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Doctors_Table = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        Doctor_Back_To_Search = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Patient_Table = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        Patient_Back_To_Search = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Search_for_Hospitale = new javax.swing.JButton();
        Patient_Search = new javax.swing.JTextField();
        Search_for_Doctor = new javax.swing.JButton();
        Search_for_Patient = new javax.swing.JButton();
        Hospitale_Search = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        DRSpecialization1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu_Panal.setBackground(new java.awt.Color(153, 204, 255));
        Menu_Panal.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                Menu_PanalComponentHidden(evt);
            }
        });

        Search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(51, 0, 51));
        Search.setText("Search");
        Search.setBorder(null);
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Hospitale.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Hospitale.setForeground(new java.awt.Color(51, 0, 51));
        Hospitale.setText("Hospitals");
        Hospitale.setBorder(null);
        Hospitale.setMaximumSize(new java.awt.Dimension(93, 29));
        Hospitale.setMinimumSize(new java.awt.Dimension(93, 29));
        Hospitale.setPreferredSize(new java.awt.Dimension(93, 29));
        Hospitale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitaleActionPerformed(evt);
            }
        });

        Doctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Doctor.setForeground(new java.awt.Color(51, 0, 51));
        Doctor.setText("Doctors");
        Doctor.setBorder(null);
        Doctor.setMaximumSize(new java.awt.Dimension(93, 29));
        Doctor.setMinimumSize(new java.awt.Dimension(93, 29));
        Doctor.setPreferredSize(new java.awt.Dimension(93, 29));
        Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorActionPerformed(evt);
            }
        });

        Patient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Patient.setForeground(new java.awt.Color(51, 0, 51));
        Patient.setText("Patients");
        Patient.setBorder(null);
        Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu_PanalLayout = new javax.swing.GroupLayout(Menu_Panal);
        Menu_Panal.setLayout(Menu_PanalLayout);
        Menu_PanalLayout.setHorizontalGroup(
            Menu_PanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Menu_PanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Patient, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hospitale, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        Menu_PanalLayout.setVerticalGroup(
            Menu_PanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Hospitale, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Patient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        getContentPane().add(Menu_Panal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 390));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel8.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel8.setText("Welcom to our System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel8)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        Hospitale_Panel.setBackground(new java.awt.Color(219, 235, 251));
        Hospitale_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Hospitale_Panel.setForeground(new java.awt.Color(255, 255, 255));
        Hospitale_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back_Hospitale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back_Hospitale.setText("Back To Menu");
        Back_Hospitale.setToolTipText("");
        Back_Hospitale.setBorder(null);
        Back_Hospitale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_HospitaleActionPerformed(evt);
            }
        });
        Hospitale_Panel.add(Back_Hospitale, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 120, -1));

        Insert_Hospitale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Insert_Hospitale.setText("Insert");
        Insert_Hospitale.setToolTipText("");
        Insert_Hospitale.setBorder(null);
        Insert_Hospitale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Insert_HospitaleMouseEntered(evt);
            }
        });
        Insert_Hospitale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_HospitaleActionPerformed(evt);
            }
        });
        Hospitale_Panel.add(Insert_Hospitale, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 85, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Hospital Name");
        Hospitale_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 120, -1));
        Hospitale_Panel.add(Hospital_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 142, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Hospital Location");
        Hospitale_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, 20));
        Hospitale_Panel.add(Hospital_Loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 142, -1));

        View_Hospitales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View_Hospitales.setText("Show Hospitals");
        View_Hospitales.setToolTipText("");
        View_Hospitales.setBorder(null);
        View_Hospitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_HospitalesActionPerformed(evt);
            }
        });
        Hospitale_Panel.add(View_Hospitales, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 133, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Hospitale_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Hospitale_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        Doctor_Panel.setBackground(new java.awt.Color(219, 235, 251));
        Doctor_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Doctor_Panel.setForeground(new java.awt.Color(255, 255, 255));
        Doctor_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back_Doctor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back_Doctor.setText("Back To Menu");
        Back_Doctor.setToolTipText("");
        Back_Doctor.setBorder(null);
        Back_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_DoctorActionPerformed(evt);
            }
        });
        Doctor_Panel.add(Back_Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 120, -1));

        Doctor_Insert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Doctor_Insert.setText("Insert");
        Doctor_Insert.setToolTipText("");
        Doctor_Insert.setBorder(null);
        Doctor_Insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Doctor_InsertMouseEntered(evt);
            }
        });
        Doctor_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doctor_InsertActionPerformed(evt);
            }
        });
        Doctor_Panel.add(Doctor_Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 85, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Doctor ID");
        Doctor_Panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 85, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Name");
        Doctor_Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 50, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Specialization");
        Doctor_Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 230, -1, -1));
        Doctor_Panel.add(Doctor_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, -1));

        View_Doctors.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View_Doctors.setText("Show Doctors");
        View_Doctors.setToolTipText("");
        View_Doctors.setBorder(null);
        View_Doctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_DoctorsActionPerformed(evt);
            }
        });
        Doctor_Panel.add(View_Doctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 133, -1));
        Doctor_Panel.add(Doctor_Tele, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 130, -1));
        Doctor_Panel.add(Doctor_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 130, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Telephone");
        Doctor_Panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 85, -1));

        DRSpecialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiologists", "Gastroenterology", "Dermatology", "Neurologist", "Oncologist", "Pediatrics", "Endocrinologists" }));
        Doctor_Panel.add(DRSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 230, 130, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Doctor_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Doctor_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel3);

        jPanel4.setBackground(new java.awt.Color(219, 235, 251));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Patient_Insert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Patient_Insert.setText("Insert");
        Patient_Insert.setToolTipText("");
        Patient_Insert.setBorder(null);
        Patient_Insert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Patient_InsertMouseEntered(evt);
            }
        });
        Patient_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_InsertActionPerformed(evt);
            }
        });
        jPanel4.add(Patient_Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 85, -1));

        View_Patients.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View_Patients.setText("Show Patients");
        View_Patients.setToolTipText("");
        View_Patients.setBorder(null);
        View_Patients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_PatientsActionPerformed(evt);
            }
        });
        jPanel4.add(View_Patients, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 133, -1));

        Back_Patients.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back_Patients.setText("Back To Menu");
        Back_Patients.setToolTipText("");
        Back_Patients.setBorder(null);
        Back_Patients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_PatientsActionPerformed(evt);
            }
        });
        jPanel4.add(Back_Patients, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 120, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Patient ID");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 110, -1));

        Patient_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_IDActionPerformed(evt);
            }
        });
        jPanel4.add(Patient_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 142, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Patient Name");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 110, 20));

        Patient_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_AgeActionPerformed(evt);
            }
        });
        jPanel4.add(Patient_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 142, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Telephone");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, -1));
        jPanel4.add(Patient_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 142, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Age");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 30, -1));

        Patient_Tele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_TeleActionPerformed(evt);
            }
        });
        jPanel4.add(Patient_Tele, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 142, -1));

        jTabbedPane1.addTab("tab6", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hosts_Table.setBackground(new java.awt.Color(219, 235, 251));
        Hosts_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital Name", "Location"
            }
        ));
        jScrollPane4.setViewportView(Hosts_Table);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 320));

        jPanel17.setBackground(new java.awt.Color(219, 235, 251));

        Hospitale_Back_To_Search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hospitale_Back_To_Search.setText("Back");
        Hospitale_Back_To_Search.setToolTipText("");
        Hospitale_Back_To_Search.setBorder(null);
        Hospitale_Back_To_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hospitale_Back_To_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(192, 192, 192)
                    .addComponent(Hospitale_Back_To_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(Hospitale_Back_To_Search)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        jPanel5.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 470, 60));

        jTabbedPane1.addTab("tab9", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Doctors_Table.setBackground(new java.awt.Color(219, 235, 251));
        Doctors_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Specialization"
            }
        ));
        jScrollPane5.setViewportView(Doctors_Table);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 464, 320));

        jPanel18.setBackground(new java.awt.Color(219, 235, 251));

        Doctor_Back_To_Search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Doctor_Back_To_Search.setText("Back");
        Doctor_Back_To_Search.setToolTipText("");
        Doctor_Back_To_Search.setBorder(null);
        Doctor_Back_To_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doctor_Back_To_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel18Layout.createSequentialGroup()
                    .addGap(192, 192, 192)
                    .addComponent(Doctor_Back_To_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel18Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(Doctor_Back_To_Search)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 470, 60));

        jTabbedPane1.addTab("tab10", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Patient_Table.setBackground(new java.awt.Color(219, 235, 251));
        Patient_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Age"
            }
        ));
        jScrollPane6.setViewportView(Patient_Table);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 320));

        jPanel19.setBackground(new java.awt.Color(219, 235, 251));

        Patient_Back_To_Search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Patient_Back_To_Search.setText("Back");
        Patient_Back_To_Search.setToolTipText("");
        Patient_Back_To_Search.setBorder(null);
        Patient_Back_To_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_Back_To_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(Patient_Back_To_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Patient_Back_To_Search)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 470, 60));

        jTabbedPane1.addTab("tab11", jPanel7);

        jPanel8.setBackground(new java.awt.Color(219, 235, 251));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Search_for_Hospitale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search_for_Hospitale.setText("Serach");
        Search_for_Hospitale.setToolTipText("");
        Search_for_Hospitale.setBorder(null);
        Search_for_Hospitale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Search_for_HospitaleMouseEntered(evt);
            }
        });
        Search_for_Hospitale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_for_HospitaleActionPerformed(evt);
            }
        });
        jPanel8.add(Search_for_Hospitale, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 85, -1));

        Patient_Search.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Patient_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        Patient_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Patient_SearchMouseClicked(evt);
            }
        });
        Patient_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_SearchActionPerformed(evt);
            }
        });
        jPanel8.add(Patient_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 160, 30));

        Search_for_Doctor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search_for_Doctor.setText("Serach");
        Search_for_Doctor.setToolTipText("");
        Search_for_Doctor.setBorder(null);
        Search_for_Doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Search_for_DoctorMouseEntered(evt);
            }
        });
        Search_for_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_for_DoctorActionPerformed(evt);
            }
        });
        jPanel8.add(Search_for_Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 85, -1));

        Search_for_Patient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Search_for_Patient.setText("Serach");
        Search_for_Patient.setToolTipText("");
        Search_for_Patient.setBorder(null);
        Search_for_Patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Search_for_PatientMouseEntered(evt);
            }
        });
        Search_for_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_for_PatientActionPerformed(evt);
            }
        });
        jPanel8.add(Search_for_Patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 85, -1));

        Hospitale_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        Hospitale_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hospitale_SearchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Hospitale_SearchMouseExited(evt);
            }
        });
        Hospitale_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hospitale_SearchActionPerformed(evt);
            }
        });
        jPanel8.add(Hospitale_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 160, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Search For Patient");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 140, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Search For Hospital");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 140, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Search For Doctor");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 130, 30));

        DRSpecialization1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiologists", "Gastroenterology", "Dermatology", "Neurologist", "Oncologist", "Pediatrics", "Endocrinologists" }));
        jPanel8.add(DRSpecialization1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 160, -1));

        jTabbedPane1.addTab("tab8", jPanel8);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -30, 470, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_SearchActionPerformed

    private void HospitaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitaleActionPerformed
        // TODO add your handling code here:
        //Books_Panal.setVisible(true);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_HospitaleActionPerformed

    private void DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        //DefaultTableModel BooksTable = (DefaultTableModel) Books_Table.getModel();
        //BooksTable.setRowCount(0);
    }//GEN-LAST:event_DoctorActionPerformed

    private void PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_PatientActionPerformed

    private void Menu_PanalComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Menu_PanalComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_PanalComponentHidden

    private void Back_HospitaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_HospitaleActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Back_HospitaleActionPerformed

    private void Insert_HospitaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Insert_HospitaleMouseEntered
        // TODO add your handling code here
    }//GEN-LAST:event_Insert_HospitaleMouseEntered

    private void Insert_HospitaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_HospitaleActionPerformed
        // TODO add your handling code here:
        String name = Hospital_Name.getText().trim();
        String loc = Hospital_Loc.getText().trim();
        Hospital hos = new Hospital(name, loc);
        hospitals.add(hos);
        String message = "Inserted";
        String title = "Message";
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(null, message, title, messageType);
    }//GEN-LAST:event_Insert_HospitaleActionPerformed

    private void View_HospitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_HospitalesActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
        // sort first;

        int n = hospitals.size();
        boolean swapped;
        for (int j = 0; j < n; j++) {
            swapped = false;
            for (int i = 1; i < n; i++) {
                if (hospitals.get(i - 1).Name.compareTo(hospitals.get(i).Name) > 0) {
                    // Swap elements
                    Hospital temp = hospitals.get(i - 1);
                    hospitals.set(i - 1, hospitals.get(i));
                    hospitals.set(i, temp);
                    swapped = true;
                }
            }
            if (!swapped) {
                break;
            }
        }
        //Refresh BooksTable  
        DefaultTableModel Hosts = (DefaultTableModel) Hosts_Table.getModel();
        Hosts.setRowCount(0);

        for (Hospital item : hospitals) {
            String Name = item.Name;
            String Loc = item.Location;

            //String array to store BooksTable Data into jtable
            String HostData[] = {Name, Loc};
            DefaultTableModel HostTemp = (DefaultTableModel) Hosts_Table.getModel();

            //add String array BooksData into JTable
            HostTemp.addRow(HostData);
        }
    }//GEN-LAST:event_View_HospitalesActionPerformed

    private void Back_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_DoctorActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Back_DoctorActionPerformed

    private void Doctor_InsertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Doctor_InsertMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Doctor_InsertMouseEntered

    private void Doctor_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doctor_InsertActionPerformed
        // TODO add your handling code here:
        String id = Doctor_ID.getText().trim();
        String name = Doctor_Name.getText().trim();
        String Tele = Doctor_Tele.getText().trim();
        String specialization = DRSpecialization.getSelectedItem().toString();
        Doctor doc = new Doctor(id, name, Tele, specialization);
        addElement(doctors, specialization, doc);
        String message = "Inserted";
        String title = "Message";
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(null, message, title, messageType);
    }//GEN-LAST:event_Doctor_InsertActionPerformed

    private void View_DoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_DoctorsActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
        DefaultTableModel Docs = (DefaultTableModel) Doctors_Table.getModel();
        Docs.setRowCount(0);
        String s[] = {"Cardiologists", "Gastroenterology", "Dermatology", "Neurologist", "Oncologist", "Pediatrics", "Endocrinologists"};
        for (int i = 0; i < s.length; i++) {
            if (doctors.containsKey(s[i])) {
                for (Doctor item : doctors.get(s[i])) {
                    String id = item.Id;
                    String name = item.Name;
                    String tele = item.Tele;
                    String specialization = item.Specialization;
                    String DocData[] = {id, name, tele, specialization};
                    DefaultTableModel DocTemp = (DefaultTableModel) Doctors_Table.getModel();
                    DocTemp.addRow(DocData);
                }
            }
        }
    }//GEN-LAST:event_View_DoctorsActionPerformed

    private void Patient_InsertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patient_InsertMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_InsertMouseEntered

    private void Patient_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_InsertActionPerformed
        // TODO add your handling code here:
        String id = Patient_ID.getText().trim();
        String name = Patient_Name.getText().trim();
        String Tele = Patient_Tele.getText().trim();
        int age = Integer.parseInt(Patient_Age.getText().trim());
        Patient pat = new Patient(id, name, Tele, age);
        patients.add(pat);
        String message = "Inserted";
        String title = "Message";
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(null, message, title, messageType);
    }//GEN-LAST:event_Patient_InsertActionPerformed

    private void View_PatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_PatientsActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6);
        // avg = nlogn, wort = n**2, best = n

        quickSort(patients, 0, patients.size() - 1);

        DefaultTableModel pts = (DefaultTableModel) Patient_Table.getModel();
        pts.setRowCount(0);

        for (Patient item : patients) {
            String id = item.Id;
            String name = item.Name;
            String tele = item.Tele;
            int age = item.Age;

            Object ptsData[] = {id, name, tele, age};

            DefaultTableModel ptsTemp = (DefaultTableModel) Patient_Table.getModel();

            ptsTemp.addRow(ptsData);
        }

    }//GEN-LAST:event_View_PatientsActionPerformed

    private void Back_PatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_PatientsActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Back_PatientsActionPerformed

    private void Patient_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_IDActionPerformed

    private void Patient_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_AgeActionPerformed

    private void Patient_TeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_TeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_TeleActionPerformed

    private void Search_for_HospitaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_for_HospitaleMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_for_HospitaleMouseEntered

    private void Search_for_HospitaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_for_HospitaleActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);

        int n = hospitals.size();
        boolean swapped;
        for (int j = 0; j < n; j++) {
            swapped = false;
            for (int i = 1; i < n; i++) {
                if (hospitals.get(i - 1).Name.compareTo(hospitals.get(i).Name) > 0) {
                    // Swap elements
                    Hospital temp = hospitals.get(i - 1);
                    hospitals.set(i - 1, hospitals.get(i));
                    hospitals.set(i, temp);
                    swapped = true;
                }
            }
            if (!swapped) {
                break;
            }
        }

        String s = Hospitale_Search.getText().trim();
        int find = binarySearchH(hospitals, s);

        if (find != -1) {
            DefaultTableModel Hosts = (DefaultTableModel) Hosts_Table.getModel();
            Hosts.setRowCount(0);
            String HostData[] = {hospitals.get(find).Name, hospitals.get(find).Location};
            DefaultTableModel HostTemp = (DefaultTableModel) Hosts_Table.getModel();

            HostTemp.addRow(HostData);
        } else {
            String message = "Not Found";
            String title = "Message";
            int messageType = JOptionPane.INFORMATION_MESSAGE;
            JOptionPane.showMessageDialog(null, message, title, messageType);
        }
    }//GEN-LAST:event_Search_for_HospitaleActionPerformed

    private void Patient_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Patient_SearchMouseClicked
        // TODO add your handling code here:
        Patient_Search.setText(null);
    }//GEN-LAST:event_Patient_SearchMouseClicked

    private void Patient_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_SearchActionPerformed

    private void Search_for_DoctorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_for_DoctorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_for_DoctorMouseEntered

    private void Search_for_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_for_DoctorActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);

        String Key = DRSpecialization1.getSelectedItem().toString().trim();

        if (doctors.containsKey(Key)) {
            DefaultTableModel Docs = (DefaultTableModel) Doctors_Table.getModel();
            Docs.setRowCount(0);
            ArrayList<Doctor> LS = doctors.get(Key);
            Collections.sort(LS);
            for (Doctor item : LS) {
                String id = item.Id;
                String name = item.Name;
                String tele = item.Tele;
                String specialization = item.Specialization;
                String DocData[] = {id, name, tele, specialization};
                DefaultTableModel DocTemp = (DefaultTableModel) Doctors_Table.getModel();
                DocTemp.addRow(DocData);
            }
        } else {
            String message = "Not Found";
            String title = "Message";
            int messageType = JOptionPane.INFORMATION_MESSAGE;
            JOptionPane.showMessageDialog(null, message, title, messageType);
        }

    }//GEN-LAST:event_Search_for_DoctorActionPerformed

    private void Search_for_PatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_for_PatientMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_for_PatientMouseEntered

    private void Search_for_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_for_PatientActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6);
        quickSort(patients, 0, patients.size()-1);
        String s = Patient_Search.getText().trim();
        int find = binarySearchP(patients, s);
        if (find != -1) {
            DefaultTableModel pts = (DefaultTableModel) Patient_Table.getModel();
            pts.setRowCount(0);
            Patient item = patients.get(find);
            String id = item.Id;
            String name = item.Name;
            String tele = item.Tele;
            int age = item.Age;

            Object ptsData[] = {id, name, tele, age};

            DefaultTableModel ptsTemp = (DefaultTableModel) Patient_Table.getModel();

            ptsTemp.addRow(ptsData);
        } else {
            String message = "Not Found";
            String title = "Message";
            int messageType = JOptionPane.INFORMATION_MESSAGE;
            JOptionPane.showMessageDialog(null, message, title, messageType);
        }
    }//GEN-LAST:event_Search_for_PatientActionPerformed

    private void Hospitale_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hospitale_SearchMouseClicked
        // TODO add your handling code here:
        Hospitale_Search.setText(null);
    }//GEN-LAST:event_Hospitale_SearchMouseClicked

    private void Hospitale_SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hospitale_SearchMouseExited
        // TODO add your handling code here:;
    }//GEN-LAST:event_Hospitale_SearchMouseExited

    private void Hospitale_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hospitale_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hospitale_SearchActionPerformed

    private void Hospitale_Back_To_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hospitale_Back_To_SearchActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_Hospitale_Back_To_SearchActionPerformed

    private void Doctor_Back_To_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doctor_Back_To_SearchActionPerformed
        // TODO add your handling code here:)
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_Doctor_Back_To_SearchActionPerformed

    private void Patient_Back_To_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_Back_To_SearchActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_Patient_Back_To_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Doctor;
    private javax.swing.JButton Back_Hospitale;
    private javax.swing.JButton Back_Patients;
    private javax.swing.JComboBox<String> DRSpecialization;
    private javax.swing.JComboBox<String> DRSpecialization1;
    private javax.swing.JButton Doctor;
    private javax.swing.JButton Doctor_Back_To_Search;
    private javax.swing.JTextField Doctor_ID;
    private javax.swing.JButton Doctor_Insert;
    private javax.swing.JTextField Doctor_Name;
    private javax.swing.JPanel Doctor_Panel;
    private javax.swing.JTextField Doctor_Tele;
    private javax.swing.JTable Doctors_Table;
    private javax.swing.JTextField Hospital_Loc;
    private javax.swing.JTextField Hospital_Name;
    private javax.swing.JButton Hospitale;
    private javax.swing.JButton Hospitale_Back_To_Search;
    private javax.swing.JPanel Hospitale_Panel;
    private javax.swing.JTextField Hospitale_Search;
    private javax.swing.JTable Hosts_Table;
    private javax.swing.JButton Insert_Hospitale;
    private javax.swing.JPanel Menu_Panal;
    private javax.swing.JButton Patient;
    private javax.swing.JTextField Patient_Age;
    private javax.swing.JButton Patient_Back_To_Search;
    private javax.swing.JTextField Patient_ID;
    private javax.swing.JButton Patient_Insert;
    private javax.swing.JTextField Patient_Name;
    private javax.swing.JTextField Patient_Search;
    private javax.swing.JTable Patient_Table;
    private javax.swing.JTextField Patient_Tele;
    private javax.swing.JButton Search;
    private javax.swing.JButton Search_for_Doctor;
    private javax.swing.JButton Search_for_Hospitale;
    private javax.swing.JButton Search_for_Patient;
    private javax.swing.JButton View_Doctors;
    private javax.swing.JButton View_Hospitales;
    private javax.swing.JButton View_Patients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
